### ISSUE TITLE
Upgrade Handlebars to 1.1.2

### ISSUE THREAD

**Issue by pdokas** [YahooArchive/locator-handlebars#14]
Handlebars 1.1 was released on 11/3, and they’ve issued two revisions since then to get to 1.1.2.

Could locator-handlebars update to this version?

https://github.com/wycats/handlebars.js/blob/master/release-notes.md

**Comment by pdokas** [comment]
Related YUI3 issue: https://github.com/yui/yui3/issues/1433

**Comment by caridy** [comment]
once you upgrade YUI to use the new handlebars, no change in `locator-handlebars` is necessary.

it is also important to highlight that you can patch handlebars manually by passing the new handlebars engine into the config for the plugin, and that will overrule the one coming from `Y.Handlebars`. More details here:

https://github.com/yahoo/locator-handlebars/blob/master/README.md#configuration
