### ISSUE TITLE
Template registration with locator-handlebars

### ISSUE THREAD

**Issue by clarle** [YahooArchive/locator-handlebars#6]
I'm coming across an issue that doesn't occur with `locator-dust` with `locator-handlebars`.

To handle partials in `locator-handlebars`, we need to either pass the partial template functions in when rendering or register them with Handlebars ahead of time.

A possible way of solving this problem is to have a public method in `Y.Template` that  lets us determine if a template with a given name exists in the registry, and return it if it does.  That lets us use our already loaded partials when registering a template that relies on them.  This doesn't exist yet, but it's easy to implement.

An alternative solution is to use `Y.Handlebars.registerPartial` and register every template that we use as a possible partial.  I feel this causes a bit of data duplication though.

@caridy, @ericf, thoughts?

**Comment by ericf** [comment]
`Y.Handlebars.registerPartial()` is dangerous. From my experience it's much better to pass along the partials with each call to render a template. This is what I do in `express3-handlebars`: https://github.com/ericf/express3-handlebars/blob/master/lib/express-handlebars.js#L193

**Comment by caridy** [comment]
`locator-handlebars` already does that for you. It uses the internals of the handlebars parser to know the names of the partials used by a particular template, then it synthetically define them as yui modules dependencies, and passed them into the render method as a second argument.

https://github.com/yahoo/locator-handlebars/blob/master/lib/plugin.js#L87

I wonder what's the problem you're seeing? and how to reproduce it?

The interesting thing, is that `locator-dust` doesn't do that just yet, we need to look into the internals of the parser to determine the list of partials needed to fulfill the yui modules dependencies.

**Comment by clarle** [comment]
@caridy I'm trying to replace the part that you're pointing out with the `Y.Template.register` API.  

It's not possible to do that unless I directly access `Y.Template._registry`, which I don't think is the right thing to do.

**Comment by caridy** [comment]
That is correct! you need references to some of the registered templates to provision the `partials` structure, and so far there is not a way to do that other than thru `_registry`.
